server:
  port: "8281"
  read_timeout: "120s"
  write_timeout: "120s"
  idle_timeout: "180s"

services:
  auth:
    base_url: "http://localhost:8081"
    timeout: "30s"
    retries: 2
  communication:
    base_url: "http://localhost:8082"
    timeout: "30s"
    retries: 2
  company:
    base_url: "http://localhost:8083"
    timeout: "30s"
    retries: 2
  terms:
    base_url: "http://localhost:8084"
    timeout: "30s"
    retries: 2
  user:
    base_url: "http://localhost:8085"
    timeout: "30s"
    retries: 2

rabbitmq:
  host: "localhost"
  port: 5672
  user: "guest"
  password: "guest"
  vhost: "/"
  exchange: "ms-communication-exchange-local"
  #exchange: "ms-communication-exchange-dev"
  routing_key: "communication.message.send"
  durable: true
  auto_delete: false
  audit:
    enabled: true
    exchange: "srv-audit-exchange-local"
    routing_key: "audit.event"
    durable: true


jwt:
  issuer: "keepguard"
  audience: "keepguard-api"
  jwks_url: ""
  signing_key: ""

redis:
  host: ${REDIS_HOST:localhost}
  port: 6379
  password: ${REDIS_PASSWORD:}
  db: 0

rate_limit:
  enabled: true
  rules:
    login:
      limit: 100
      window: 60s
    forgot_password:
      limit: 100
      window: 60s
    device_challenge_send:
      limit: 100
      window: 60s
    device_challenge_verify:
      limit: 100
      window: 60s
    reset_password:
      limit: 100
      window: 60s
    change_password:
      limit: 100
      window: 60s
    refresh:
      limit: 200
      window: 60s
    validate:
      limit: 500
      window: 60s
    logout:
      limit: 100
      window: 60s
    device_quick_revoke:
      limit: 100
      window: 60s
    device_blacklist:
      limit: 100
      window: 60s
    account_lifecycle:
      limit: 10
      window: 60s
    default:
      limit: 500
      window: 60s

metrics:
  enabled: true
  scrape_path: "/metrics"
  port: "9092"

log:
  level: "debug"
  format: "json"

env: "local"
