apiVersion: v1
kind: Service
metadata:
  name: bff-auth-service
  labels:
    app: bff-auth
spec:
  selector:
    app: bff-auth
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
