package dto

import appdto "github.com/keepguard/bff-auth/internal/application/dto"

type AvailableMfaChannelDTO = appdto.AvailableMfaChannelDTO
type AuthResponseDTO = appdto.AuthResponseDTO
type RefreshTokenResponseDTO = appdto.RefreshTokenResponseDTO
type DeviceChallengeSendRequestDTO = appdto.DeviceChallengeSendRequestDTO
type DeviceChallengeVerifyRequestDTO = appdto.DeviceChallengeVerifyRequestDTO
type DeviceSessionDTO = appdto.DeviceSessionDTO
type DeviceBlacklistDTO = appdto.DeviceBlacklistDTO
type AddDeviceBlacklistRequestDTO = appdto.AddDeviceBlacklistRequestDTO
type AdminAddDeviceBlacklistRequestDTO = appdto.AdminAddDeviceBlacklistRequestDTO
type AdminDeviceBlacklistEntryDTO = appdto.AdminDeviceBlacklistEntryDTO
type PaginatedDeviceBlacklistResponseDTO = appdto.PaginatedDeviceBlacklistResponseDTO
type PaginatedDeviceSessionResponseDTO = appdto.PaginatedDeviceSessionResponseDTO
